// Fichas de personagem (dados puros — usados pelas fichas SVG em docs/personagens/).
export const BIOS = {
  lampi: {
    name: 'Lampi',
    title: 'O Lampião Corajoso',
    role: 'Herói · Jogável',
    palette: ['#ff8a2a', '#ffd27a', '#d9a441', '#e0412f', '#6a3b22'],
    personality: 'Impulsivo, otimista e sempre o primeiro a pular. Acha que coragem é só um tipo de luz que a gente acende por dentro.',
    ability: 'Equilibrado em tudo. O pulo duplo solta uma cambalhota de fogo.',
    design: 'Uma lanterna de papel viva: corpo de gomos que brilha por dentro, tampa de latão com alça e uma chaminha no topo. Cachecol vermelho para leitura de movimento.',
    quote: 'Bora brilhar!',
    stats: { velocidade: 3, pulo: 3, peso: 2, tracao: 3 },
  },
  nuvi: {
    name: 'Nuvi',
    title: 'A Nuvem Sonhadora',
    role: 'Heroína · Jogável',
    palette: ['#f4f9ff', '#6ab7ff', '#b48cff', '#ffcf3a', '#3a2f5a'],
    personality: 'Calma, poética e sempre um pouco sonolenta. Conhece (quase) todas as estrelas pelo nome.',
    ability: 'Segure o pulo no ar para planar com o guarda-chuva de lavanda.',
    design: 'Corpo de nuvem feito de bolhas macias com brilho "sheen", gotinha de chuva como topete, galochas amarelas para contraste e o guarda-chuva como silhueta única.',
    quote: 'Eu estava sonhando com estrelas…',
    stats: { velocidade: 2, pulo: 3, peso: 1, tracao: 3 },
  },
  musgo: {
    name: 'Musgo',
    title: 'O Gigante Gentil',
    role: 'Herói · Jogável',
    palette: ['#a39e93', '#5fae45', '#7fdc4f', '#ff7ab8', '#b6ff8a'],
    personality: 'Fala pouco, cuida de todo mundo e adora plantinhas. O mais forte do grupo — e o mais delicado.',
    ability: 'Pesado: a patada no chão cria uma onda de choque bem maior.',
    design: 'Pedra facetada (flat shading) com capa de musgo, runa verde brilhante no peito e um broto com flor rosa que balança com molas (animação secundária).',
    quote: 'Hm. Juntos.',
    stats: { velocidade: 2, pulo: 2, peso: 3, tracao: 3 },
  },
  zuca: {
    name: 'Zuca',
    title: 'A Inventora de Corda',
    role: 'Heroína · Jogável',
    palette: ['#ff4fa3', '#2fd0c4', '#d9814a', '#ffe45c', '#0d0a1c'],
    personality: 'Hiperativa, fala rápido e calcula probabilidades para tudo. Constrói geringonças com peças de relógio.',
    ability: 'A mais rápida da turma — mas escorrega nas curvas (pouca tração).',
    design: 'Robô de lata dos anos 50: corpo rosa metálico com clearcoat, cabeça-tela com olhos de LED, antena com lâmpada e chave de corda que gira mais rápido quando corre.',
    quote: 'Calculando… 97% de chance de dar certo!',
    stats: { velocidade: 3, pulo: 3, peso: 1, tracao: 1 },
  },
  candeia: {
    name: 'Vó Candeia',
    title: 'A Guardiã do Grande Farol',
    role: 'Mentora · Narradora',
    palette: ['#ffcf7a', '#7a4a8a', '#b8574a', '#e8a86a', '#f4f1ec'],
    personality: 'Sábia, doce e firme. Criou os quatro aprendizes e acende o Grande Farol há mais noites do que se pode contar.',
    ability: 'Guia os heróis pelo rádio de luz da sua candeia (a lamparina de óleo que dá nome a ela).',
    design: 'Vaga-lume idosa: xale de lã, óculos redondos, coque branco, antenas com pontas acesas e a candeia sempre na mão.',
    quote: 'Juntos, iluminam o céu inteiro.',
    stats: null,
  },
  nox: {
    name: 'Nox',
    title: 'A Mariposa do Eclipse',
    role: 'Antagonista · Chefe final',
    palette: ['#241638', '#5a2f8f', '#ff5ac8', '#ffd6f6', '#ffcf5a'],
    personality: 'A sombra do Grande Farol. Passou a vida inteira ao redor da luz sem nunca poder tocá-la — e a solidão virou fome.',
    ability: 'Orbes de sombra teleguiados, mergulho com onda de choque, rajadas de asas e invocação de Sombrinhas.',
    design: 'Mariposa gigante com asas de "olhos" brilhantes (shader procedural), pelagem escura e o núcleo dourado da Chama Primordial no peito — o ponto fraco. Na redenção, encolhe e ganha tons de lavanda.',
    quote: 'Todos sempre olham para a luz. Ninguém olha para a sombra!',
    stats: null,
  },
};

export const BIO_ORDER = ['lampi', 'nuvi', 'musgo', 'zuca', 'candeia', 'nox'];
